POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "xdsjsd3",
  "password": "xdsjsdjsd"
}

###
GET http://localhost:8080/system/users?begin=0
Accept: application/json

###
POST http://localhost:8080/system/user
Content-Type: application/json

{
  "username": "xdsjsd5",
  "password": "xdsjsd",
  "phoneNumber": "17000000001",
  "locked": false
}

###
DELETE http://localhost:8080/system/user
Content-Type: application/json

[
  25,
  28
]

###
PUT http://localhost:8080/system/user
Content-Type: application/json

{
  "id": 23,
  "phoneNumber": "17000000004",
  "locked": true
}

###
GET http://localhost:8080/system/user/1
Accept: application/json

###
