package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.SysMetadataGroupDO;
import com.sequarius.titan.sample.domain.SysMetadataGroupDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysMetadataGroupDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    long countByExample(SysMetadataGroupDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int deleteByExample(SysMetadataGroupDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int insert(SysMetadataGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int insertSelective(SysMetadataGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    List<SysMetadataGroupDO> selectByExample(SysMetadataGroupDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    SysMetadataGroupDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysMetadataGroupDO record, @Param("example") SysMetadataGroupDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByExample(@Param("record") SysMetadataGroupDO record, @Param("example") SysMetadataGroupDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByPrimaryKeySelective(SysMetadataGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata_group
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByPrimaryKey(SysMetadataGroupDO record);
}