package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.SysMetadataDO;
import com.sequarius.titan.sample.domain.SysMetadataDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysMetadataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    long countByExample(SysMetadataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int deleteByExample(SysMetadataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int insert(SysMetadataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int insertSelective(SysMetadataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    List<SysMetadataDO> selectByExample(SysMetadataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    SysMetadataDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysMetadataDO record, @Param("example") SysMetadataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByExample(@Param("record") SysMetadataDO record, @Param("example") SysMetadataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByPrimaryKeySelective(SysMetadataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_metadata
     *
     * @mbg.generated Thu Apr 09 16:20:27 CST 2020
     */
    int updateByPrimaryKey(SysMetadataDO record);
}