package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.SysRoleDO;
import com.sequarius.titan.sample.domain.SysRoleDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    long countByExample(SysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int deleteByExample(SysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int insert(SysRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int insertSelective(SysRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    List<SysRoleDO> selectByExample(SysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    SysRoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRoleDO record, @Param("example") SysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int updateByExample(@Param("record") SysRoleDO record, @Param("example") SysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int updateByPrimaryKeySelective(SysRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Feb 06 14:35:27 CST 2020
     */
    int updateByPrimaryKey(SysRoleDO record);
}