package com.sequarius.repository;

import com.sequarius.domain.SysUserDO;
import com.sequarius.domain.SysUserDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    long countByExample(SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int deleteByExample(SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int insert(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int insertSelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    List<SysUserDO> selectByExample(SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    SysUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysUserDO record, @Param("example") SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int updateByExample(@Param("record") SysUserDO record, @Param("example") SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int updateByPrimaryKeySelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Jan 30 22:38:08 CST 2020
     */
    int updateByPrimaryKey(SysUserDO record);
}